project_name = "deplo-images"

# release target branch settings
[release_targets]
release = { type = "Branch", patterns = ["main"] }

[workflows]
# no additional workflows

[secrets]
SUNTOMI_VCS_ACCOUNT = { env = "SUNTOMI_VCS_ACCOUNT" }
SUNTOMI_VCS_ACCOUNT_EMAIL = { env = "SUNTOMI_VCS_ACCOUNT_EMAIL" }
SUNTOMI_VCS_ACCOUNT_KEY = { env = "SUNTOMI_VCS_ACCOUNT_KEY" }

[vars]

[vcs]
type = "github"
email = "${SUNTOMI_VCS_ACCOUNT_EMAIL}"
account = "${SUNTOMI_VCS_ACCOUNT}"
key = "${SUNTOMI_VCS_ACCOUNT_KEY}"

[ci.default]
type = "ghaction"
account = "${SUNTOMI_VCS_ACCOUNT}"
key = "${SUNTOMI_VCS_ACCOUNT_KEY}"

[jobs.aws]
on = { changed = ["aws/Dockerfile"] }
runner = { type = "machine", os = "linux", local_fallback = { image = "docker:25.0.1", shell = "sh" } }
command = """
echo ${SUNTOMI_VCS_ACCOUNT_KEY} | docker login ghcr.io -u ${SUNTOMI_VCS_ACCOUNT} --password-stdin
docker buildx build --push --platform linux/amd64,linux/arm64 -t ghcr.io/suntomi/images:aws -f aws/Dockerfile aws
"""
